// accumulated shared stuffs to avoid circular references of modules

import { createSignal } from "solid-js"

// re-exporting math functions so that minifiers can optimize better
export const { abs, cos, floor, min, PI, random, sin } = Math

/**
 * Evaluates a media query
 * @param query the media query
 * @returns whether the media query matches
 */
export const media = (query: string) => matchMedia(query).matches

const SECOND = 1000 // in milliseconds
const MINUTE = 60 * SECOND
const HOUR = 60 * MINUTE
export const DAY = 24 * HOUR

/**
 * Current date and time as of when the webpage is loaded
 */
const now = new Date()

/**
 * Today’s local date as number of days since Unix
 * @note Each puzzle reveals at 05:00 AM (local time)
 */
export const today = floor((now.getTime() - now.getTimezoneOffset() * MINUTE - 5 * HOUR) / DAY)

/**
 * Creates an array of a specified length, populated using a provided function.
 *
 * @param length The desired length of the array.
 * @param fn Function to generate each element, receiving the value (always `undefined`) and the index.
 * @returns An array of length `length`, with each element generated by `fn`.
 */
export function createArrayOfLength<U = never>(length: number): (U | undefined)[]
export function createArrayOfLength<U>(length: number, fn: (v: never, k: number) => U): U[]
export function createArrayOfLength<U>(length: number, fn?: (v: never, k: number) => U) {
	// @ts-ignore: fn can be optional
	return Array.from({ length }, fn)
}

// signal for whether the dialog has been shown
export const [isDialogShown, setDialogShown] = createSignal(false)
