// accumulated shared stuffs to avoid circular references of modules

const SECOND = 1000 // in milliseconds
const MINUTE = 60 * SECOND
const HOUR = 60 * MINUTE
const DAY = 24 * HOUR

/**
 * Current date and time as of when the webpage is loaded
 */
export const now = new Date()

/**
 * Today’s local date as number of days since Unix
 * @note Each puzzle reveals at 05:00 AM (local time)
 */
export const today = Math.floor((now.getTime() - now.getTimezoneOffset() * MINUTE - 5 * HOUR) / DAY)

/**
 * Creates an array of a specified length, populated using a provided function.
 *
 * @param length The desired length of the array.
 * @param fn Function to generate each element, receiving the value (always `undefined`) and the index.
 * @returns An array of length `length`, with each element generated by `fn`.
 */
export const createArrayOfLength =
	// @ts-ignore: fn can be optional
	<U = never>(length: number, fn?: (v: never, k: number) => U) => Array.from({ length }, fn)
